title: "Exonymos"
description: "Simple and clean project showcase and blog site for exonymos."
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.webp"

# Social Links
email: exonymos@gmail.com
github_username: exonymos
twitter_username: exonymos
instagram_username:
linkedin_username:
facebook_username:
mastodon_username: Exonymos

# External API
giscus_repo: "Exonymos/Projects"
giscus_repoId: "R_kgDOJfktVA"
giscus_category: "General Old"
giscus_categoryId: "DIC_kwDOJfktVM4Cnfiu"
goatcounter_code: exonymos
google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
